stages:
  - lint
  - test
  - deploy

lint-client-job:
  image: node:18-alpine
  stage: lint
  script:
    - cd client
    - npm install
    - cd src
    - eslint .

#lint-server-job:
#  image: node:18-alpine
#  stage: lint
#  script:
#    - cd server
#    - npm install
#    - cd src
#    - eslint .

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
